"""Tests for the CSV round-trip that carries human verdicts into the sheets.

The value of these tests is narrow and specific: this script is the only writer of
``human_verdict``, the data it writes cannot be regenerated by anything (a person had
to look at the image), and it runs against files that are 100% unannotated today. So
the failure modes worth pinning are all about *not losing or corrupting* that data.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
_SPEC = importlib.util.spec_from_file_location(
    "human_verdict_io", REPO_ROOT / "scripts" / "human_verdict_io.py"
)
hvio = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(hvio)


@pytest.fixture()
def sheet(tmp_path, monkeypatch):
    """A three-row dg_pairs-shaped sheet, rooted in tmp_path."""
    rel = Path("data/human_validation_fairness/pairs.jsonl")
    path = tmp_path / rel
    path.parent.mkdir(parents=True)
    rows = [
        {
            "pair_key": f"scene_{i}__gender",
            "attribute": "gender",
            "left": "man",
            "right": "woman",
            "image": f"pairs/scene_{i}.jpg",
            "auditors_agree": i != 1,
            "human_verdict": "",
        }
        for i in range(3)
    ]
    path.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    monkeypatch.setattr(hvio, "REPO_ROOT", tmp_path)
    return path


def _read(path: Path) -> list[dict]:
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def _write_csv(path: Path, rows: list[tuple[str, str]]) -> None:
    lines = ["# comment line the reader must skip", "key,image,verdict,note"]
    lines += [f"{k},img.jpg,{v}," for k, v in rows]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8-sig")


def test_export_then_import_round_trips(sheet, tmp_path):
    csv_path = tmp_path / "v.csv"
    assert hvio.cmd_export("dg_pairs", csv_path, include_done=False) == 0

    text = csv_path.read_text(encoding="utf-8-sig")
    assert "valid | moved | noflip | noperson" in text  # the vocabulary reaches the annotator
    assert "auditors_agree" in text  # the column that says which rows matter most

    _write_csv(csv_path, [("scene_0__gender", "valid"), ("scene_1__gender", "moved")])
    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=False) == 0

    got = {r["pair_key"]: r["human_verdict"] for r in _read(sheet)}
    assert got == {"scene_0__gender": "valid", "scene_1__gender": "moved", "scene_2__gender": ""}


def test_import_rejects_unknown_label_and_writes_nothing(sheet, tmp_path):
    """A typo must not reach the JSONL: construct_validity counts unknown labels in the
    denominator but never the numerator, so a silent typo lowers the pass rate."""
    before = sheet.read_bytes()
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid"), ("scene_1__gender", "vaild")])

    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=False) == 1
    assert sheet.read_bytes() == before  # all-or-nothing: even the good row is not written


def test_import_rejects_unknown_key_and_writes_nothing(sheet, tmp_path):
    before = sheet.read_bytes()
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid"), ("no_such_scene", "valid")])

    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=False) == 1
    assert sheet.read_bytes() == before


def test_import_is_a_noop_when_nothing_changed(sheet, tmp_path):
    """Re-importing the same CSV must not rewrite the file -- re-serialising JSONL is
    not guaranteed to reproduce it byte-for-byte, and this data is irreplaceable."""
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid")])
    hvio.cmd_import("dg_pairs", csv_path, dry_run=False)

    after_first = sheet.read_bytes()
    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=False) == 0
    assert sheet.read_bytes() == after_first


def test_dry_run_never_writes(sheet, tmp_path):
    before = sheet.read_bytes()
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid")])

    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=True) == 0
    assert sheet.read_bytes() == before


def test_export_skips_already_annotated_rows_unless_all(sheet, tmp_path):
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid")])
    hvio.cmd_import("dg_pairs", csv_path, dry_run=False)

    pending = tmp_path / "pending.csv"
    hvio.cmd_export("dg_pairs", pending, include_done=False)
    body = pending.read_text(encoding="utf-8-sig")
    assert "scene_0__gender" not in body  # done
    assert "scene_1__gender" in body

    everything = tmp_path / "all.csv"
    hvio.cmd_export("dg_pairs", everything, include_done=True)
    assert "scene_0__gender" in everything.read_text(encoding="utf-8-sig")


def test_verdict_is_case_insensitive_and_trimmed(sheet, tmp_path):
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "  VALID  ")])
    assert hvio.cmd_import("dg_pairs", csv_path, dry_run=False) == 0
    assert _read(sheet)[0]["human_verdict"] == "valid"


def test_other_fields_survive_untouched(sheet, tmp_path):
    csv_path = tmp_path / "v.csv"
    _write_csv(csv_path, [("scene_0__gender", "valid")])
    hvio.cmd_import("dg_pairs", csv_path, dry_run=False)

    row = _read(sheet)[0]
    assert row["attribute"] == "gender"
    assert row["left"] == "man"
    assert row["image"] == "pairs/scene_0.jpg"
    assert row["auditors_agree"] is True
